# Generated by Django 3.2 on 2022-02-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_auto_20220205_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitre',
            name='nom_chapitre',
            field=models.TextField(max_length=250),
        ),
    ]
